using System.Collections.Generic;

namespace Travel.Web.ApiModels
{
    // ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
    public class LibrosDTO : CreateLibroDTO
    {
        public long ISBN  { get; set; }
        public string Autor  { get; set; }
        public string Editorial  { get; set; }
    }

    // Creation DTOs should not include an ID if the ID will be generated by the back end
    public class CreateLibroDTO
    {
        public int EditorialesId { get; set; }
        public string Titulo { get; set; }
        public string Sinopsis { get; set; }
        public string NPaginas { get; set; }
    }
}
